[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = ['py', 'python']
hook_add = '''
  let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['py', 'python']
hook_add = '''
  " エラー行に表示するマーク
  let g:ale_sign_error = '⨉'
  let g:ale_sign_warning = '⚠'
  " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  " エラー表示の列を常時表示
  let g:ale_sign_column_always = 1

  " ファイルを開いたときにlint実行
  let g:ale_lint_on_enter = 1
  " ファイルを保存したときにlint実行
  let g:ale_lint_on_save = 1
  " 編集中のlintはしない
  let g:ale_lint_on_text_changed = 'never'

  " lint結果をロケーションリストとQuickFixには表示しない
  " 出てると結構うざいしQuickFixを書き換えられるのは困る
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0

  " 有効にするlinter
  let g:ale_linters = {
  \   'python': ['flake8'],
  \}

  " ALE用プレフィックス
  nnoremap [prefix] <nop>
  nmap ,   [prefix]
  xnoremap [prefix] <nop>
  xmap ,   [prefix]
  " エラー行にジャンプ
  nmap <silent> [prefix]<C-P> <Plug>(ale_previous)
  nmap <silent> [prefix]<C-N> <Plug>(ale_next)
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo = 'tomtom/tcomment_vim'
on_ft = ['javascript', 'python', 'go']

