[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = ['py', 'python']
hook_add = '''
  let g:deoplete#sources#jedi#show_docstring = 0
'''


[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo = 'tomtom/tcomment_vim'
on_ft = ['js', 'python']

