# ale {{{
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['py', 'python']
hook_add = '''
    " エラー行に表示するマーク
    let g:ale_sign_error = 'E'
    let g:ale_sign_warning = 'W'
    " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
    let g:ale_echo_msg_format = '[%linter%][%severity%] %s'
    " エラー表示の列を常時表示
    let g:ale_sign_column_always = 1

    " ファイルを開いたときにlint実行
    let g:ale_lint_on_enter = 1
    " ファイルを保存したときにlint実行
    let g:ale_lint_on_save = 1
    " 編集中のlintはしない
    let g:ale_lint_on_text_changed = 'never'

    " lint結果をロケーションリストとQuickFixには表示しない
    " 出てると結構うざいしQuickFixを書き換えられるのは困る
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 0
    let g:ale_open_list = 0
    let g:ale_keep_list_window_open = 0

    " 有効にするlinter
    let g:ale_linters = {
    \   'python': ['pylint'],
    \}
    let g:ale_fixers = {
    \   'python': ['trim_whitespace', 'isort', 'yapf'],
    \ }

    " ALE用プレフィックス
    nnoremap [prefix] <nop>
    nmap ,   [prefix]
    xnoremap [prefix] <nop>
    xmap ,   [prefix]
    " エラー行にジャンプ
    nmap <silent> [prefix]<C-P> <Plug>(ale_previous)
    nmap <silent> [prefix]<C-N> <Plug>(ale_next)
    " autoformat
    nmap <silent> [prefix]f <Plug>(ale_fix)
'''
# }}}

# echodoc {{{
[[plugins]]
repo = 'Shougo/echodoc'
on_ft = ['py']
hook_add = '''
    "set noshowmode
    "let g:echodoc_enable_at_startup = 1
    let g:echodoc#echodoc_enable_at_startup = 1
    let g:echodoc#type = 'floating'
    highlight link EchoDocFloat Pmenu
'''
# }}}

# vim-markdown {{{
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''
# }}}

# vim-toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# tcomment {{{
[[plugins]]
repo = 'tomtom/tcomment_vim'
on_ft = ['javascript', 'python', 'go', 'html', 'js', 'vue', 'sh', 'cc']
# }}}

# vim-pydocstring {{{
[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = ['python']
hook_add = '''
    let g:pydocstring_doq_path = '~/anaconda3/bin/doq'
    let g:pydocstring_formatter = 'google'
    "" ALE用プレフィックス
    "nnoremap [prefix] <nop>
    "nmap ,   [prefix]
    "xnoremap [prefix] <nop>
    "xmap ,   [prefix]
    "" エラー行にジャンプ
    "nmap <silent> [prefix]<C-P> <Plug>(ale_previous)
    "nmap <silent> [prefix]<C-N> <Plug>(ale_next)
    "" autoformat
    "nmap <silent> [prefix]f <Plug>(ale_fix)
    "vmap <silent> gp <Plug>(Pydocstring)
    "vmap pd <Plug>(pydocstring)
    nmap <silent> pd <Plug>(pydocstring)
'''
# }}}
