[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = ['py', 'python']


[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']



